version: '3.9'
services:
  blaze:
    image: samply/blaze:latest
    restart: unless-stopped
    environment:
      BASE_URL: http://localhost:8080
    ports:
      - ${BLAZE_PORT:-8080}:8080
    volumes:
      - blaze-data:/app/data
  fhir-facade:
    build: ./facade_app
    restart: unless-stopped
    environment:
      FHIR_SERVER_URL: ${FHIR_SERVER_URL:-http://blaze:8080/fhir/}
      FACADE_PORT: ${FACADE_PORT:-8082}
    ports: 
      - ${FACADE_PORT:-8082}:8082
    
volumes:
    blaze-data:
