#Add all resources that are supposed to be limited by consent status
#This must include a 'Date' Attribute with a relative Path from the Resource to a necessary Date field including its name
#As well as a similar 'Subject' field with the relative Path to a necessary Patient Identifier
Resources:
  Observation:
    Date: ""
    Subject: ""
  Appointment:
    Date: ""
    Subject: ""
  Procedure:
    Date: ""
    Subject: ""
  Patient:
    Date: ""
    Subject: ""