name: Docker Image CI

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./facade_app
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/fhir-facade:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/fhir-facade:${{ steps.prep.outputs.version }}
